name: hm_integral_app
description: A Flutter app for visualizing area under curves with AI-driven storytelling.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  google_generative_ai: ^0.4.0

  # Core
  cupertino_icons: ^1.0.6
  provider: ^6.1.2

  # Networking & configuration
  http: ^1.2.1

  # UI & animations
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  fl_chart: ^0.66.2
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - apisecure.env  # ✅ Dosya adın doğru
    - assets/content/
    - assets/animations/
    - assets/images/

  # If you add custom fonts later, define them here:
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
  #       - asset: assets/fonts/YourFont-Bold.ttf