// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABlLCM_PsdWcnijkSPJhkgem9kFmSi_Ho',
    appId: '1:285264164268:web:29084263e29e2a0cd4b609',
    messagingSenderId: '285264164268',
    projectId: 'hm-mobil-2026-acbc7',
    authDomain: 'hm-mobil-2026-acbc7.firebaseapp.com',
    storageBucket: 'hm-mobil-2026-acbc7.firebasestorage.app',
    measurementId: 'G-W0S1V4NZX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfZGkchaCT2CUaiVHHwYjM_XdwXHx5Hc8',
    appId: '1:285264164268:android:f8c074f1f416e62fd4b609',
    messagingSenderId: '285264164268',
    projectId: 'hm-mobil-2026-acbc7',
    storageBucket: 'hm-mobil-2026-acbc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcZGP4Q922jPgzbZLg6ZIjYYDqfgQ0i_A',
    appId: '1:285264164268:ios:0d82425c1702fc16d4b609',
    messagingSenderId: '285264164268',
    projectId: 'hm-mobil-2026-acbc7',
    storageBucket: 'hm-mobil-2026-acbc7.firebasestorage.app',
    iosBundleId: 'com.example.hmIntegralApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcZGP4Q922jPgzbZLg6ZIjYYDqfgQ0i_A',
    appId: '1:285264164268:ios:0d82425c1702fc16d4b609',
    messagingSenderId: '285264164268',
    projectId: 'hm-mobil-2026-acbc7',
    storageBucket: 'hm-mobil-2026-acbc7.firebasestorage.app',
    iosBundleId: 'com.example.hmIntegralApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABlLCM_PsdWcnijkSPJhkgem9kFmSi_Ho',
    appId: '1:285264164268:web:62d54acca7eb23c2d4b609',
    messagingSenderId: '285264164268',
    projectId: 'hm-mobil-2026-acbc7',
    authDomain: 'hm-mobil-2026-acbc7.firebaseapp.com',
    storageBucket: 'hm-mobil-2026-acbc7.firebasestorage.app',
    measurementId: 'G-DBW9RD4KE2',
  );
}
